### ISSUE TITLE
Mediawiki UI of http://wikifundi-es.openzim.org should be Spanish

### ISSUE THREAD

**Issue by kelson42** [offspot/wikifundi#100]
It seems this is English (per default)

**Comment by rgaudin** [comment]
@Anthere, should we do something about this ? It's the same for FR as well. User can change language but there is no default, so it's English.

I think there's an extension to use browser language as default. Or we could just have Spanish as default.

**Comment by Anthere** [comment]
Not sure about the choices, but it would definitly be better if the interface opens by default in the user language (in this case, Spanish for the Spanish version etc.)
