### ISSUE TITLE
En: the WikiFundi:Welcome page is missing

### ISSUE THREAD

**Issue by Anthere** [offspot/wikifundi#104]
This should be this page : https://en.wikipedia.org/wiki/Wikipedia:WikiProject_WikiFundi_Content/WikiFundi:Welcome
I checked in case, no one removed the category. So I do not know what’s wrong...

**Comment by Anthere** [comment]
I went ahead and did a full copy paste of the text... seems fine....
But I am curious as to why that page was simply... not created ?

**Comment by rgaudin** [comment]
FYI log says it attempted to copy it and failed due to non-JSON response from API so it's not a content issue.

**Comment by rgaudin** [comment]
Fixed
