### ISSUE TITLE
EN: disclaimer text when creating an article needs to be updated

### ISSUE THREAD

**Issue by Anthere** [offspot/wikifundi#108]
Currently, the text reads

"Please note that all contributions to WikiFundi are considered to be released under the Creative Commons Attribution Share Alike (see WikiFundi:Copyrights for details). If you do not want your writing to be edited mercilessly and redistributed at will, then do not submit it here."

But there is no WikiFundi:Copyrights page. And to be fair, what people use as licence is none of our business. 

I am tempted to say... blank this paragraph. This is true for English, French and Spanish

**Comment by rgaudin** [comment]
OK, voilà ce que ça donne ensuite
<img width="517" alt="Screen Shot 2021-09-14 at 09 32 32" src="https://user-images.githubusercontent.com/57929/133235703-d267ee3d-887b-403f-94ba-dcd9ca3e5a92.png">

Pour le lien, c'est pas nous qui le donnons, c'est visiblement construit depuis le nom du Wiki (WikiFundi:Copyright). Serait probablement judicieux de faire un rediect là bas.

**Comment by Anthere** [comment]
Ok for the link. I'll create three redirections. 
But is it possible to change the text itself ?

**Comment by rgaudin** [comment]
Nope. This is controlled by MW.

**Comment by Anthere** [comment]
bon ben... je fais 3 redirections :)
