### ISSUE TITLE
en : import of a « wrong » category

### ISSUE THREAD

**Issue by Anthere** [offspot/wikifundi#113]
This whole category should not exist at all : http://wikifundi-en.openzim.org/wiki/Category:WikiProject_WikiFundi_Content

It contains articles that should have been uploaded in the main space (and actually, they were. So they exist both in the main space and in the wikipedia space.

So, those articles should not have been uploaded. And the category should not exist. Weird... :(

**Comment by rgaudin** [comment]
For some reason, articles in this categories list themselves as template, as visible in [page info](https://en.wikipedia.org/w/index.php?title=Wikipedia:WikiProject_WikiFundi_Content/Battle_of_Sio&action=info)
<img width="653" alt="Screen_Shot_2021-09-23_at_11_33_42" src="https://user-images.githubusercontent.com/57929/134500148-7ab41322-f3ea-46b4-bfbe-0ddc4fbcdc37.png">

I could not find the reason for this so I've added a check in templates retrieval to exclude itself from the list of templates.
