### ISSUE TITLE
ES: sidebar menu

### ISSUE THREAD

**Issue by Anthere** [offspot/wikifundi#115]
When I am on the main page, I see in the menu
1. Subir archivo
Does that really work on WikiFundi ? If does not work, better not to display that as it would bring confusion
2. Citar esta página
I am not sure this will be useful, it would mostly bring confusion. Perhaps best to remove it from menu

**Comment by rgaudin** [comment]
> When I am on the main page, I see in the menu
>     1. Subir archivo
>        Does that really work on WikiFundi ? If does not work, better not to display that as it would bring confusion

Of course, that's the Upload feature.

>     2. Citar esta página
>        I am not sure this will be useful, it would mostly bring confusion. Perhaps best to remove it from menu

Removed.
