### ISSUE TITLE
ES : missing articles

### ISSUE THREAD

**Issue by Anthere** [offspot/wikifundi#116]
The following were not imported
* Mitología griega (https://es.wikipedia.org/wiki/Mitolog%C3%ADa_griega)
* Antibiótico (https://es.wikipedia.org/wiki/Antibiótico)
* Marcas corporativas de Wikipedia (https://es.wikipedia.org/wiki/Marcas_corporativas_de_Wikipedia)
Why those ? No idea...

**Comment by rgaudin** [comment]
> The following were not imported
> 
>     * Mitología griega (https://es.wikipedia.org/wiki/Mitolog%C3%ADa_griega)

It's in the [Dropped selection section](https://meta.wikimedia.org/wiki/WikiFundi/2021#Dropped_selection)

>     * Antibiótico ([https://es.wikipedia.org/wiki/Antibiótico](https://es.wikipedia.org/wiki/Antibi%C3%B3tico))

Idem

>     * Marcas corporativas de Wikipedia (https://es.wikipedia.org/wiki/Marcas_corporativas_de_Wikipedia)

Not listed anywhere on https://meta.wikimedia.org/wiki/WikiFundi/2021

Closing this. Reopen if you want them but also add them to the meta listing so it doesn't create confusion.
