### ISSUE TITLE
(ES) Missing pages

### ISSUE THREAD

**Issue by Anthere** [offspot/wikifundi#121]
Some pages were missing. I could not figure out why...
I added them manually
* http://wikifundi-es.openzim.org/wiki/Ayuda:C%C3%B3mo_editar_una_p%C3%A1gina
* http://wikifundi-es.openzim.org/wiki/Ayuda:C%C3%B3mo_dar_formato_a_una_p%C3%A1gina

**Comment by Cacucho** [comment]
The page "Colón" is included in WikiFundi/2021 as an example of  disambiguation page imported from Spanish Wikipedia. Note that It doesn't include the sufix (desambiguación) in the title as occurs with the original disambiguation page . 
Why this disambiguation page couldn't be imported to WikiFundi as well?
