### ISSUE TITLE
Image files are not all writable on exfat

### ISSUE THREAD

**Issue by kelson42** [offspot/wikifundi#72]
Kiwix-plug use exfat to store the data... and as a consequence untar the Wikfundi data complains:

```
$ tar -m --no-same-permissions --no-same-owner -xf ../cache/mediawiki_data_en_2018-06.tar.bz2
tar: data/images/7/7f/Washington,_D.C.,_April_1865_(i.e._1863?)_LCCN2013651864.tif: Cannot open: No such file or directory
tar: data/images/5/52/Brochure_Wikipédia_enseignants-chercheurs_"Utiliser_Wikipédia_avec_vos_étudiants_-_Études_de_cas".pdf: Cannot open: No such file or directory
tar: data/images/a/ad/Ambox_?.svg: Cannot open: No such file or directory
tar: data/images/e/e4/What_is_Wikipedia_Zero?.webm: Cannot open: No such file or directory
```

**Comment by kelson42** [comment]
So, we need to find a way to tell to Mediawiki to write filenames without special characters

**Comment by kelson42** [comment]
I have open a ticket here https://phabricator.wikimedia.org/T199140

**Comment by kelson42** [comment]
@rgaudin I guess we have to rename the pictures with this problem and there fore there is nothing more we can do here, right?

**Comment by rgaudin** [comment]
The upstream bug is clear and is not resolved so the workarounds are the ones listed in https://github.com/offspot/kiwix-hotspot/issues/628.

Fixing filenames in the wikifundi instance so that we produce a safe archive is more work but is what we want ; yes. Option D is faster to implement but it's a *deployed workaround*.

**Comment by kelson42** [comment]
Lets live with the manuel renaming workaround in Wikifunidi (rename file + rewrite wikicode) or deleting them (option B), I don't really think this is worth investigating more energy in something more sophisticated.
