### ISSUE TITLE
Textes à mettre à jour sur la page d'accueil FR MAX

### ISSUE THREAD

**Issue by Anthere** [offspot/wikifundi#84]
TODO : changer quelques légendes. 
Avant : 
	Wikipedia [Full text index, no video]
	Une page de Wikipedia l'encyclopédie libre
Après
	Wikipedia
	Wikipédia, l'encyclopédie libre (sans vidéos)

Avant
	Wikiquote [full text  index no video]
	Une page de Wikiquote, le recueil des citations libres
Après
	Wikiquote
	Wikiquote, le recueil des citations libres (sans vidéos)

Avant
	Wikisource [full text index no video]
	La bibliothèque libre
Après
	Wikisource
	La bibliothèque libre (sans vidéos)

Avant
Wiktionnaire [Full text index]
Après
	Wiktionnaire
	(la légende est à conserver telle quelle)

Avant
	Encyclopédie médicale WikiMed [no picture, Full texte index]
	L'encyclopédie médicale de Wikipedia
Après
	WikiMed
	L'encyclopédie médicale WikiMed (sans photos ni vidéos)

**Comment by kelson42** [comment]
@Anthere We can not do that so far, but the request is absolutly legitimate and will be part of Kiwix Hotspot 3.0, see feature request https://framagit.org/ideascube/pibox-installer/issues/235

**Comment by rgaudin** [comment]
Closing this as obsolete then
