### ISSUE TITLE
WikiFundi in Spanish

### ISSUE THREAD

**Issue by Anthere** [offspot/wikifundi#98]
Antonio has expressed the will to help make WikiFundi available in Spanish. What would be the requirements from the tech side to implement that ?

**Comment by luandro** [comment]
Would also love to start organizing to make it available in Portuguese.

**Comment by kelson42** [comment]
@luandro Why not, but please open a new ticket.

**Comment by kelson42** [comment]
@Anthere There is a few things to do but the key point is the fact that currently the meta articles and the wikipedia articles are on different wikis.

**Comment by rgaudin** [comment]
I think we have now and can open separate issues for this.
